POST http://localhost:8080/api/products
Content-Type: application/json 

{
    "title": "Iphone-14",
    "sku": "PHN-199617", 
    "priceAmount": 1000, 
    "currency": "USD", 
    "stock": 100, 
    "version": 1
}